# This is a basic workflow to help you get started with GitHub Actions

name: GitHub Actions Secret Example

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The first job in this workflow is named build-on-windows
  secrets-in-github-actions:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Step 1 - Echo out a GitHub Secret to the logs
        shell: bash
        env: 
          SECRET_VARIABLE: ${{ secrets.SECRET_TOKEN }}
        run: |

          echo The GitHub Action Secret will be filtered
          echo ${{ secrets.SECRET_TOKEN }}
          echo The GitHub Action Secret variable will be filtered
          echo $SUPER_SECRET
          echo Trick to echo GitHub Actions Secret
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'
          echo Trick to echo GitHub Actions Secret variable
          echo $SUPER_SECRET | sed 's/./& /g'

      - name: Step 2 - Use a GitHub Secret
        shell: bash
        env: 
          WHO_TO_TRUST: ${{ secrets.WORKFLOW_SECRET }}
        run: |

          echo The GitHub Action Secret will be filtered
          echo ${{ secrets.WORKFLOW_SECRET }}
          echo The GitHub Action Secret variable will be filtered
          echo $WORKFLOW_SECRET
          echo Trick to echo GitHub Actions Secret
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'
          echo Trick to echo GitHub Actions Secret variable
          echo $WHO_TO_TRUST | sed 's/./& /g'
          
      - name: Step 3 - Conditional
        shell: bash
        env: 
          WHO_TO_TRUST: ${{ secrets.WORKFLOW_SECRET }}
        run: |
          echo I know what the secret token is!
        if: ${{ secrets.WORKFLOW_SECRET }} == 'TrustNo1'

        
      - name: Step 4 - Conditional
        shell: bash
        env: 
          WHO_TO_TRUST: ${{ secrets.WORKFLOW_SECRET }}
        run: |
          echo I don't know the secret token:  
        if: ${{ secrets.WORKFLOW_SECRET }} != 'TrustNo1'  

