# This is a basic github workflow to get started

name: Getting started

# controls when the action will be trigger. Workflow triggeres on push or pull request events
# as mentiond below workflow will triggere only in the main branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# a workflow is made with one or more than one jobs that can be run sequentially or in parallel

jobs:
  # This workflow contains a single job called build
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      # checks-out the current repository under $GITHUB_WORKSPACE, so our job can access this repo codes
      - uses: actions/checkout@v2

      # Runs a single line command using runner shell
      - name: Run a one-line script
        run: echo welcome to devops trainning by Visualpath

      # Run a set of commands using the runner shell
      - name: Run a multi-line script
        run: |
          echo What is in the directory ?
          ls -la 
          echo Is java is installed ?
          java -version
          echo Is Git installed ?
          git --version
          echo what about the build tools ?
          mvn --version
          ant -version

